export const filters = {
    theme: [
        { id: 'island-tour', label: 'Island Tour' },
        { id: 'land-tour', label: 'Land Tour' },
        { id: 'safari', label: 'Safari' }
    ],
    activity: [
        { id: 'swimming', label: 'Swimming' },
        { id: 'running', label: 'Running' },
        { id: 'elephant-care', label: 'Elephant Care' }
    ],
    vehicle: [
        { id: 'yacht', label: 'Yacht' },
        { id: 'car', label: 'Car' },
        { id: 'speedboat', label: 'Speedboat' },
        { id: 'safari-truck', label: 'Safari Truck' }
    ],
    features: [
        { id: 'transfer', label: 'Transfer' },
        { id: 'local-food', label: 'Local Food' }
    ]
};

export const categories = [
    { id: 'all', label: 'All' },
    { id: 'tours', label: 'Tours' },
    { id: 'tickets', label: 'Tickets' },
    { id: 'rent', label: 'Rent' },
    { id: 'transfer', label: 'Transfer' },
];

export const locations = [
    { id: "all", name: "All" },
    { id: "kenya", name: "Kenya" },
    { id: "new-york", name: "New York" },
    { id: "rome", name: "Rome" },
    { id: "switzerland", name: "Switzerland" },
    { id: "maldives", name: "Maldives" },
    { id: "tokyo", name: "Tokyo" },
    { id: "brazil", name: "Brazil" },
    { id: "dubai", name: "Dubai" },
    { id: "paris", name: "Paris" },
    { id: "england", name: "England" },
    { id: "chicago", name: "Chicago" },
    { id: "greece", name: "Greece" },
    { id: "los-angeles", name: "Los Angeles" },
    { id: "london", name: "London" },
    { id: "madrid", name: "Madrid" },
    { id: "rio-de-janeiro", name: "Rio de Janeiro" },
    { id: "vienna", name: "Vienna" },
    { id: "berlin", name: "Berlin" },
    { id: "amsterdam", name: "Amsterdam" },
    { id: "venice", name: "Venice" },
    { id: "barcelona", name: "Barcelona" },
    { id: "usa", name: "USA" },
    { id: "singapore", name: "Singapore" },
    { id: "san-francisco", name: "San Francisco" },
    { id: "las-vegas", name: "Las Vegas" }
];

export const tours = [
    // Tours (12 adet) - Theme, Activity, Vehicle & Features Filters'a Göre Düzenlendi
    {
        id: 1,
        title: "Safari Adventure",
        discount: 20,
        originalPrice: 200,
        discountedPrice: 160,
        rating: 4.5,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "safari",
        activity: ["elephant-care"],
        vehicle: "safari-truck",
        features: "transfer",
        category: "tours",
        description: "Experience an unforgettable safari adventure in the wild.",
        location: "Kenya"
    },
    {
        id: 2,
        title: "City Lights Tour",
        discount: 0,
        originalPrice: 150,
        discountedPrice: 150,
        rating: 4.2,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "tours",
        description: "Discover the vibrant city nightlife and hidden gems.",
        location: "New York"
    },
    {
        id: 3,
        title: "Historical Journey",
        discount: 10,
        originalPrice: 180,
        discountedPrice: 162,
        rating: 4.3,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "safari-truck",
        features: "local-food",
        category: "tours",
        description: "Step back in time with a journey through history.",
        location: "Rome"
    },
    {
        id: 4,
        title: "Mountain Escape",
        discount: 0,
        originalPrice: 220,
        discountedPrice: 220,
        rating: 4.7,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "safari-truck",
        features: "transfer",
        category: "tours",
        description: "Escape to the serene mountains for a refreshing retreat.",
        location: "Switzerland"
    },
    {
        id: 5,
        title: "Beach Paradise",
        discount: 0,
        originalPrice: 190,
        discountedPrice: 190,
        rating: 4.6,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "island-tour",
        activity: ["swimming"],
        vehicle: "speedboat",
        features: "local-food",
        category: "tours",
        description: "Relax on pristine sandy beaches and soak in the sun.",
        location: "Maldives"
    },
    {
        id: 6,
        title: "Cultural Experience",
        discount: 15,
        originalPrice: 160,
        discountedPrice: 136,
        rating: 4.4,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "safari-truck",
        features: "local-food",
        category: "tours",
        description: "Immerse yourself in local culture with authentic experiences.",
        location: "Tokyo"
    },
    {
        id: 7,
        title: "Forest Trek",
        discount: 0,
        originalPrice: 210,
        discountedPrice: 210,
        rating: 4.1,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "safari-truck",
        features: "transfer",
        category: "tours",
        description: "Explore lush green forests and reconnect with nature.",
        location: "Brazil"
    },
    {
        id: 8,
        title: "Desert Safari",
        discount: 25,
        originalPrice: 230,
        discountedPrice: 172.5,
        rating: 4.8,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "safari",
        activity: ["elephant-care"],
        vehicle: "safari-truck",
        features: "transfer",
        category: "tours",
        description: "Adventure in the golden sands with an exhilarating desert safari.",
        location: "Dubai"
    },
    {
        id: 9,
        title: "River Cruise",
        discount: 0,
        originalPrice: 170,
        discountedPrice: 170,
        rating: 4.0,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "island-tour",
        activity: ["swimming"],
        vehicle: "yacht",
        features: "local-food",
        category: "tours",
        description: "Enjoy a tranquil cruise along a scenic river.",
        location: "Paris"
    },
    {
        id: 10,
        title: "Countryside Retreat",
        discount: 0,
        originalPrice: 200,
        discountedPrice: 200,
        rating: 4.3,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "safari-truck",
        features: "local-food",
        category: "tours",
        description: "Unwind in the peaceful and charming countryside.",
        location: "England"
    },
    {
        id: 11,
        title: "Urban Exploration",
        discount: 0,
        originalPrice: 140,
        discountedPrice: 140,
        rating: 4.1,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "tours",
        description: "Discover hidden gems in the urban jungle.",
        location: "Chicago"
    },
    {
        id: 12,
        title: "Island Hopping",
        discount: 10,
        originalPrice: 250,
        discountedPrice: 225,
        rating: 4.5,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "island-tour",
        activity: ["swimming"],
        vehicle: "speedboat",
        features: "local-food",
        category: "tours",
        description: "Hop between picturesque islands and enjoy coastal beauty.",
        location: "Greece"
    },
    // Tickets (6 adet)
    {
        id: 13,
        title: "Rock Concert",
        discount: 0,
        originalPrice: 80,
        discountedPrice: 80,
        rating: 4.7,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "tickets",
        description: "Experience electrifying rock music in a live concert.",
        location: "Los Angeles"
    },
    {
        id: 14,
        title: "Theater Play",
        discount: 5,
        originalPrice: 60,
        discountedPrice: 57,
        rating: 4.2,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "car",
        features: "local-food",
        category: "tickets",
        description: "Enjoy a captivating theatrical performance on stage.",
        location: "London"
    },
    {
        id: 15,
        title: "Sports Event",
        discount: 0,
        originalPrice: 90,
        discountedPrice: 90,
        rating: 4.0,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "tickets",
        description: "Cheer on your favorite team in an exciting sports event.",
        location: "Madrid"
    },
    {
        id: 16,
        title: "Comedy Show",
        discount: 0,
        originalPrice: 50,
        discountedPrice: 50,
        rating: 4.5,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "car",
        features: "local-food",
        category: "tickets",
        description: "Laugh out loud at a hilarious and engaging comedy show.",
        location: "Chicago"
    },
    {
        id: 17,
        title: "Festival Entry",
        discount: 0,
        originalPrice: 70,
        discountedPrice: 70,
        rating: 4.3,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "tickets",
        description: "Join the vibrant atmosphere of a local festival.",
        location: "Rio de Janeiro"
    },
    {
        id: 18,
        title: "Opera Night",
        discount: 0,
        originalPrice: 100,
        discountedPrice: 100,
        rating: 4.6,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "car",
        features: "local-food",
        category: "tickets",
        description: "Experience a night of timeless opera and elegance.",
        location: "Vienna"
    },
    // Rent (6 adet)
    {
        id: 19,
        title: "Luxury Car Rental",
        discount: 10,
        originalPrice: 300,
        discountedPrice: 270,
        rating: 4.7,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "safari",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "rent",
        description: "Rent a luxury car for an exceptional and stylish drive.",
        location: "Dubai"
    },
    {
        id: 20,
        title: "Economy Car Rental",
        discount: 0,
        originalPrice: 100,
        discountedPrice: 100,
        rating: 4.0,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "rent",
        description: "Affordable and efficient car rental service for everyday needs.",
        location: "Berlin"
    },
    {
        id: 21,
        title: "Bike Rental",
        discount: 0,
        originalPrice: 40,
        discountedPrice: 40,
        rating: 4.3,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "island-tour",
        activity: ["swimming"],
        vehicle: "safari-truck", // Filtrede bisiklet yok, en yakın araç
        features: "local-food",
        category: "rent",
        description: "Rent a bike to explore the city at your own pace.",
        location: "Amsterdam"
    },
    {
        id: 22,
        title: "Boat Rental",
        discount: 15,
        originalPrice: 250,
        discountedPrice: 212.5,
        rating: 4.6,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "island-tour",
        activity: ["swimming"],
        vehicle: "yacht",
        features: "transfer",
        category: "rent",
        description: "Enjoy a day out on a boat with all safety measures in place.",
        location: "Venice"
    },
    {
        id: 23,
        title: "Scooter Rental",
        discount: 0,
        originalPrice: 30,
        discountedPrice: 30,
        rating: 4.1,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car", // Filtrede scooter yok
        features: "transfer",
        category: "rent",
        description: "Zip around the city effortlessly with a scooter rental.",
        location: "Barcelona"
    },
    {
        id: 24,
        title: "RV Rental",
        discount: 0,
        originalPrice: 350,
        discountedPrice: 350,
        rating: 4.5,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "safari-truck",
        features: "local-food",
        category: "rent",
        description: "Travel in comfort and style with an RV rental experience.",
        location: "USA"
    },
    // Transfer (6 adet)
    {
        id: 25,
        title: "Airport Transfer",
        discount: 0,
        originalPrice: 60,
        discountedPrice: 60,
        rating: 4.4,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Enjoy a seamless transfer from the airport to your destination.",
        location: "Singapore"
    },
    {
        id: 26,
        title: "Hotel Shuttle",
        discount: 0,
        originalPrice: 50,
        discountedPrice: 50,
        rating: 4.2,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Convenient shuttle service to get you to your hotel hassle-free.",
        location: "Tokyo"
    },
    {
        id: 27,
        title: "Private Transfer",
        discount: 20,
        originalPrice: 100,
        discountedPrice: 80,
        rating: 4.8,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "safari",
        activity: ["swimming"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Experience a private and luxurious transfer tailored for you.",
        location: "Paris"
    },
    {
        id: 28,
        title: "City Transfer",
        discount: 0,
        originalPrice: 40,
        discountedPrice: 40,
        rating: 4.1,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Efficient and reliable city transfer services for your convenience.",
        location: "New York"
    },
    {
        id: 29,
        title: "Corporate Shuttle",
        discount: 0,
        originalPrice: 70,
        discountedPrice: 70,
        rating: 4.3,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["elephant-care"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Reliable shuttle service ideal for corporate events and meetings.",
        location: "San Francisco"
    },
    {
        id: 30,
        title: "Event Transfer",
        discount: 0,
        originalPrice: 55,
        discountedPrice: 55,
        rating: 4.0,
        image: "https://cdn.getyourguide.com/img/tour/3913d25fe5736dc60d825d22f03a56ad4b35a0d08bf504e76a7533667c8bf547.png/146.jpg",
        theme: "land-tour",
        activity: ["running"],
        vehicle: "car",
        features: "transfer",
        category: "transfer",
        description: "Quick and comfortable transfer service tailored for events.",
        location: "Las Vegas"
    }
];